services:
  # Backend API Service
  - type: web
    name: gcet-food-ordering-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://23r11a6208:QNuUIm6CazuAzsbb@cluster0.fs4ph.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: SESSION_SECRET
        sync: false
      - key: FAST2SMS_API_KEY
        sync: false
      - key: CLIENT_URL
        value: https://gcet-food-ordering-frontend.onrender.com
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/$1
      - type: rewrite
        source: /api/health
        destination: /api/health

  # Frontend Static Site
  - type: static
    name: gcet-food-ordering-frontend
    env: static
    buildCommand: chmod +x frontend-build.sh && ./frontend-build.sh
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://gcet-food-ordering-backend.onrender.com 